"""Add transactions table

Revision ID: 2f576ab60281
Revises: 11e2457a634e
Create Date: 2026-09-22 18:08:52.983741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f576ab60281'
down_revision: Union[str, Sequence[str], None] = '11e2457a634e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('amount', sa.Double(precision=2), nullable=False),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('recipient', sa.String(), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('balance', sa.Double(precision=2), nullable=False),
    sa.Column('sms', sa.String(), nullable=False),
    sa.Column('cost', sa.Double(precision=2), nullable=False),
    sa.Column('action', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['tracked_addresses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_code'), 'transactions', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_code'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
