"""Update timestamp to integer data type

Revision ID: 46ce78e128c0
Revises: 2f576ab60281
Create Date: 2026-09-27 17:05:56.029501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46ce78e128c0'
down_revision: Union[str, Sequence[str], None] = '2f576ab60281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'timestamp',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.BigInteger(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'timestamp',
               existing_type=sa.BigInteger(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    # ### end Alembic commands ###
